version: '3'

services:
  web:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./code:/code:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    image: php:5-fpm-alpine
    volumes:
      - ./code:/code:ro
